version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl and use pipenv to install dependencies
            sudo python setup.py sdist bdist_wheel
            sudo pip install pipenv
            pipenv install dist/debuggy-1.1.2-py3-none-any.whl
            pipenv install pytest


  pypi_publish:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl, install twine and publish to PyPI
            python setup.py sdist bdist_wheel
            sudo pip install pipenv
            pipenv install twine
            pipenv run twine upload dist/*
workflows:
  build_test_publish:
    jobs:
      - build_test
      - pypi_publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - main